Fixing compilation issues on specific product: undefined reference to TaskStackManager::getActiveTask()
caused by VELAPLATFO-21485

Signed-off-by: pengchen1 <pengchen1@xiaomi.com>